function names = dataSetNames()


names = { 
    'breast-cancer-wisconsin',...
    'diabetic_retinopathy',...
    'ecoli',...
    'glass',...
    'haberman',...
    'ionosphere',...
    'iris',...
    'liver',...
    'segment',...
    'sonar',...
    'thyroid',...
    'vehicle',...
    'wine',...
};


end